// Code generated by "stringer -type Accessibility"; DO NOT EDIT.

package ec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Local-0]
	_ = x[Global-1]
}

const _Accessibility_name = "LocalGlobal"

var _Accessibility_index = [...]uint8{0, 5, 11}

func (i Accessibility) String() string {
	if i < 0 || i >= Accessibility(len(_Accessibility_index)-1) {
		return "Accessibility(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Accessibility_name[_Accessibility_index[i]:_Accessibility_index[i+1]]
}
