// Code generated by "stringer -type ComponentState"; DO NOT EDIT.

package ec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComponentState_Birth-0]
	_ = x[ComponentState_Attach-1]
	_ = x[ComponentState_Awake-2]
	_ = x[ComponentState_Start-3]
	_ = x[ComponentState_Living-4]
	_ = x[ComponentState_Detach-5]
	_ = x[ComponentState_Shut-6]
	_ = x[ComponentState_Death-7]
}

const _ComponentState_name = "ComponentState_BirthComponentState_AttachComponentState_AwakeComponentState_StartComponentState_LivingComponentState_DetachComponentState_ShutComponentState_Death"

var _ComponentState_index = [...]uint8{0, 20, 41, 61, 81, 102, 123, 142, 162}

func (i ComponentState) String() string {
	if i < 0 || i >= ComponentState(len(_ComponentState_index)-1) {
		return "ComponentState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComponentState_name[_ComponentState_index[i]:_ComponentState_index[i+1]]
}
