// Code generated by eventcode--decl_file=component_event.go gen_emit --package=ec --default_auto=true; DO NOT EDIT.

package ec

import (
	"fmt"
	event "kit.golaxy.org/golaxy/event"
	iface "kit.golaxy.org/golaxy/util/iface"
)

type iAutoEventComponentDestroySelf interface {
	EventComponentDestroySelf() event.IEvent
}

func BindEventComponentDestroySelf(auto iAutoEventComponentDestroySelf, delegate EventComponentDestroySelf) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.BindEvent[EventComponentDestroySelf](auto.EventComponentDestroySelf(), delegate)
}

func BindEventComponentDestroySelfWithPriority(auto iAutoEventComponentDestroySelf, delegate EventComponentDestroySelf, priority int32) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.BindEventWithPriority[EventComponentDestroySelf](auto.EventComponentDestroySelf(), delegate, priority)
}

func emitEventComponentDestroySelf(auto iAutoEventComponentDestroySelf, comp Component) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventComponentDestroySelf()).Emit(func(delegate iface.Cache) bool {
		iface.Cache2Iface[EventComponentDestroySelf](delegate).OnComponentDestroySelf(comp)
		return true
	})
}
