// Code generated by "stringer -type ComponentState"; DO NOT EDIT.

package ec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ComponentState_Born-0]
	_ = x[ComponentState_Attached-1]
	_ = x[ComponentState_Awakened-2]
	_ = x[ComponentState_Enabling-3]
	_ = x[ComponentState_Idle-4]
	_ = x[ComponentState_Starting-5]
	_ = x[ComponentState_Alive-6]
	_ = x[ComponentState_Detaching-7]
	_ = x[ComponentState_Shutting-8]
	_ = x[ComponentState_Disabling-9]
	_ = x[ComponentState_Dead-10]
	_ = x[ComponentState_Destroyed-11]
}

const _ComponentState_name = "ComponentState_BornComponentState_AttachedComponentState_AwakenedComponentState_EnablingComponentState_IdleComponentState_StartingComponentState_AliveComponentState_DetachingComponentState_ShuttingComponentState_DisablingComponentState_DeadComponentState_Destroyed"

var _ComponentState_index = [...]uint16{0, 19, 42, 65, 88, 107, 130, 150, 174, 197, 221, 240, 264}

func (i ComponentState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ComponentState_index)-1 {
		return "ComponentState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ComponentState_name[_ComponentState_index[idx]:_ComponentState_index[idx+1]]
}
