/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc eventtab --name=componentEventTab; DO NOT EDIT.

package ec

import (
	event "git.golaxy.org/core/event"
)

type IComponentEventTab interface {
	EventComponentEnableChanged() event.IEvent
	EventComponentDestroy() event.IEvent
}

var (
	_componentEventTabId = event.DeclareEventTabIdT[componentEventTab]()
	EventComponentEnableChangedId = _componentEventTabId + 0
	EventComponentDestroyId = _componentEventTabId + 1
)

type componentEventTab [2]event.Event

func (eventTab *componentEventTab) SetPanicHandling(autoRecover bool, reportError chan error) {
	for i := range *eventTab {
		(*eventTab)[i].SetPanicHandling(autoRecover, reportError)
	}
}

func (eventTab *componentEventTab) SetRecursion(recursion event.EventRecursion) {
	(*eventTab)[0].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[1].SetRecursion(event.EventRecursion_Allow)
}

func (eventTab *componentEventTab) SetEnable(b bool) {
	for i := range *eventTab {
		(*eventTab)[i].SetEnable(b)
	}
}

func (eventTab *componentEventTab) UnbindAll() {
	for i := range *eventTab {
		(*eventTab)[i].UnbindAll()
	}
}

func (eventTab *componentEventTab) Ctrl() event.IEventCtrl {
	return eventTab
}

func (eventTab *componentEventTab) Event(id uint64) event.IEvent {
	if _componentEventTabId != id & 0xFFFFFFFF00000000 {
		return nil
	}
	pos := id & 0xFFFFFFFF
	if pos >= uint64(len(*eventTab)) {
		return nil
	}
	switch pos {
	case 0:
		(*eventTab)[0].SetRecursion(event.EventRecursion_Allow)
	case 1:
		(*eventTab)[1].SetRecursion(event.EventRecursion_Allow)
	}
	return &(*eventTab)[pos]
}

func (eventTab *componentEventTab) EventComponentEnableChanged() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[0]
}

func (eventTab *componentEventTab) EventComponentDestroy() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[1]
}
