/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc eventtab --name=entityTreeNodeEventTab; DO NOT EDIT.

package ec

import (
	event "git.golaxy.org/core/event"
)

type IEntityTreeNodeEventTab interface {
	EventTreeNodeAddChild() event.IEvent
	EventTreeNodeRemoveChild() event.IEvent
	EventTreeNodeAttachParent() event.IEvent
	EventTreeNodeDetachParent() event.IEvent
	EventTreeNodeMoveTo() event.IEvent
}

var (
	_entityTreeNodeEventTabId = event.DeclareEventTabIdT[entityTreeNodeEventTab]()
	EventTreeNodeAddChildId = _entityTreeNodeEventTabId + 0
	EventTreeNodeRemoveChildId = _entityTreeNodeEventTabId + 1
	EventTreeNodeAttachParentId = _entityTreeNodeEventTabId + 2
	EventTreeNodeDetachParentId = _entityTreeNodeEventTabId + 3
	EventTreeNodeMoveToId = _entityTreeNodeEventTabId + 4
)

type entityTreeNodeEventTab [5]event.Event

func (eventTab *entityTreeNodeEventTab) SetPanicHandling(autoRecover bool, reportError chan error) {
	for i := range *eventTab {
		(*eventTab)[i].SetPanicHandling(autoRecover, reportError)
	}
}

func (eventTab *entityTreeNodeEventTab) SetRecursion(recursion event.EventRecursion) {
	(*eventTab)[0].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[1].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[2].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[3].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[4].SetRecursion(event.EventRecursion_Allow)
}

func (eventTab *entityTreeNodeEventTab) SetEnable(b bool) {
	for i := range *eventTab {
		(*eventTab)[i].SetEnable(b)
	}
}

func (eventTab *entityTreeNodeEventTab) UnbindAll() {
	for i := range *eventTab {
		(*eventTab)[i].UnbindAll()
	}
}

func (eventTab *entityTreeNodeEventTab) Ctrl() event.IEventCtrl {
	return eventTab
}

func (eventTab *entityTreeNodeEventTab) Event(id uint64) event.IEvent {
	if _entityTreeNodeEventTabId != id & 0xFFFFFFFF00000000 {
		return nil
	}
	pos := id & 0xFFFFFFFF
	if pos >= uint64(len(*eventTab)) {
		return nil
	}
	switch pos {
	case 0:
		(*eventTab)[0].SetRecursion(event.EventRecursion_Allow)
	case 1:
		(*eventTab)[1].SetRecursion(event.EventRecursion_Allow)
	case 2:
		(*eventTab)[2].SetRecursion(event.EventRecursion_Allow)
	case 3:
		(*eventTab)[3].SetRecursion(event.EventRecursion_Allow)
	case 4:
		(*eventTab)[4].SetRecursion(event.EventRecursion_Allow)
	}
	return &(*eventTab)[pos]
}

func (eventTab *entityTreeNodeEventTab) EventTreeNodeAddChild() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[0]
}

func (eventTab *entityTreeNodeEventTab) EventTreeNodeRemoveChild() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[1]
}

func (eventTab *entityTreeNodeEventTab) EventTreeNodeAttachParent() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[2]
}

func (eventTab *entityTreeNodeEventTab) EventTreeNodeDetachParent() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[3]
}

func (eventTab *entityTreeNodeEventTab) EventTreeNodeMoveTo() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[4]
}
