// Code generated by eventcode--decl_file=entity_event.go gen_emit --package=ec --default_auto=true; DO NOT EDIT.

package ec

import (
	"fmt"
	event "kit.golaxy.org/golaxy/event"
	iface "kit.golaxy.org/golaxy/util/iface"
)

type iAutoEventEntityDestroySelf interface {
	EventEntityDestroySelf() event.IEvent
}

func BindEventEntityDestroySelf(auto iAutoEventEntityDestroySelf, delegate EventEntityDestroySelf) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.BindEvent[EventEntityDestroySelf](auto.EventEntityDestroySelf(), delegate)
}

func BindEventEntityDestroySelfWithPriority(auto iAutoEventEntityDestroySelf, delegate EventEntityDestroySelf, priority int32) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.BindEventWithPriority[EventEntityDestroySelf](auto.EventEntityDestroySelf(), delegate, priority)
}

func emitEventEntityDestroySelf(auto iAutoEventEntityDestroySelf, entity Entity) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventEntityDestroySelf()).Emit(func(delegate iface.Cache) bool {
		iface.Cache2Iface[EventEntityDestroySelf](delegate).OnEntityDestroySelf(entity)
		return true
	})
}
