/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc event; DO NOT EDIT.

package ec

import (
	event "git.golaxy.org/core/event"
	"git.golaxy.org/core/utils/uid"
)

type iAutoEventTreeNodeAddChild interface {
	EventTreeNodeAddChild() event.IEvent
}

func BindEventTreeNodeAddChild(auto iAutoEventTreeNodeAddChild, subscriber EventTreeNodeAddChild, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventTreeNodeAddChild](auto.EventTreeNodeAddChild(), subscriber, priority...)
}

func _EmitEventTreeNodeAddChild(auto iAutoEventTreeNodeAddChild, entity Entity, childId uid.Id) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventTreeNodeAddChild()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventTreeNodeAddChild](subscriber).OnTreeNodeAddChild(entity, childId)
		return true
	})
}

func _EmitEventTreeNodeAddChildWithInterrupt(auto iAutoEventTreeNodeAddChild, interrupt func(entity Entity, childId uid.Id) bool, entity Entity, childId uid.Id) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventTreeNodeAddChild()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(entity, childId) {
				return false
			}
		}
		event.Cache2Iface[EventTreeNodeAddChild](subscriber).OnTreeNodeAddChild(entity, childId)
		return true
	})
}

func HandleEventTreeNodeAddChild(fun func(entity Entity, childId uid.Id)) EventTreeNodeAddChildHandler {
	return EventTreeNodeAddChildHandler(fun)
}

type EventTreeNodeAddChildHandler func(entity Entity, childId uid.Id)

func (h EventTreeNodeAddChildHandler) OnTreeNodeAddChild(entity Entity, childId uid.Id) {
	h(entity, childId)
}

type iAutoEventTreeNodeRemoveChild interface {
	EventTreeNodeRemoveChild() event.IEvent
}

func BindEventTreeNodeRemoveChild(auto iAutoEventTreeNodeRemoveChild, subscriber EventTreeNodeRemoveChild, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventTreeNodeRemoveChild](auto.EventTreeNodeRemoveChild(), subscriber, priority...)
}

func _EmitEventTreeNodeRemoveChild(auto iAutoEventTreeNodeRemoveChild, entity Entity, childId uid.Id) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventTreeNodeRemoveChild()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventTreeNodeRemoveChild](subscriber).OnTreeNodeRemoveChild(entity, childId)
		return true
	})
}

func _EmitEventTreeNodeRemoveChildWithInterrupt(auto iAutoEventTreeNodeRemoveChild, interrupt func(entity Entity, childId uid.Id) bool, entity Entity, childId uid.Id) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventTreeNodeRemoveChild()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(entity, childId) {
				return false
			}
		}
		event.Cache2Iface[EventTreeNodeRemoveChild](subscriber).OnTreeNodeRemoveChild(entity, childId)
		return true
	})
}

func HandleEventTreeNodeRemoveChild(fun func(entity Entity, childId uid.Id)) EventTreeNodeRemoveChildHandler {
	return EventTreeNodeRemoveChildHandler(fun)
}

type EventTreeNodeRemoveChildHandler func(entity Entity, childId uid.Id)

func (h EventTreeNodeRemoveChildHandler) OnTreeNodeRemoveChild(entity Entity, childId uid.Id) {
	h(entity, childId)
}

type iAutoEventTreeNodeAttachParent interface {
	EventTreeNodeAttachParent() event.IEvent
}

func BindEventTreeNodeAttachParent(auto iAutoEventTreeNodeAttachParent, subscriber EventTreeNodeAttachParent, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventTreeNodeAttachParent](auto.EventTreeNodeAttachParent(), subscriber, priority...)
}

func _EmitEventTreeNodeAttachParent(auto iAutoEventTreeNodeAttachParent, entity Entity, parentId uid.Id) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventTreeNodeAttachParent()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventTreeNodeAttachParent](subscriber).OnTreeNodeAttachParent(entity, parentId)
		return true
	})
}

func _EmitEventTreeNodeAttachParentWithInterrupt(auto iAutoEventTreeNodeAttachParent, interrupt func(entity Entity, parentId uid.Id) bool, entity Entity, parentId uid.Id) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventTreeNodeAttachParent()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(entity, parentId) {
				return false
			}
		}
		event.Cache2Iface[EventTreeNodeAttachParent](subscriber).OnTreeNodeAttachParent(entity, parentId)
		return true
	})
}

func HandleEventTreeNodeAttachParent(fun func(entity Entity, parentId uid.Id)) EventTreeNodeAttachParentHandler {
	return EventTreeNodeAttachParentHandler(fun)
}

type EventTreeNodeAttachParentHandler func(entity Entity, parentId uid.Id)

func (h EventTreeNodeAttachParentHandler) OnTreeNodeAttachParent(entity Entity, parentId uid.Id) {
	h(entity, parentId)
}

type iAutoEventTreeNodeDetachParent interface {
	EventTreeNodeDetachParent() event.IEvent
}

func BindEventTreeNodeDetachParent(auto iAutoEventTreeNodeDetachParent, subscriber EventTreeNodeDetachParent, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventTreeNodeDetachParent](auto.EventTreeNodeDetachParent(), subscriber, priority...)
}

func _EmitEventTreeNodeDetachParent(auto iAutoEventTreeNodeDetachParent, entity Entity, parentId uid.Id) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventTreeNodeDetachParent()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventTreeNodeDetachParent](subscriber).OnTreeNodeDetachParent(entity, parentId)
		return true
	})
}

func _EmitEventTreeNodeDetachParentWithInterrupt(auto iAutoEventTreeNodeDetachParent, interrupt func(entity Entity, parentId uid.Id) bool, entity Entity, parentId uid.Id) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventTreeNodeDetachParent()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(entity, parentId) {
				return false
			}
		}
		event.Cache2Iface[EventTreeNodeDetachParent](subscriber).OnTreeNodeDetachParent(entity, parentId)
		return true
	})
}

func HandleEventTreeNodeDetachParent(fun func(entity Entity, parentId uid.Id)) EventTreeNodeDetachParentHandler {
	return EventTreeNodeDetachParentHandler(fun)
}

type EventTreeNodeDetachParentHandler func(entity Entity, parentId uid.Id)

func (h EventTreeNodeDetachParentHandler) OnTreeNodeDetachParent(entity Entity, parentId uid.Id) {
	h(entity, parentId)
}

type iAutoEventTreeNodeMoveTo interface {
	EventTreeNodeMoveTo() event.IEvent
}

func BindEventTreeNodeMoveTo(auto iAutoEventTreeNodeMoveTo, subscriber EventTreeNodeMoveTo, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventTreeNodeMoveTo](auto.EventTreeNodeMoveTo(), subscriber, priority...)
}

func _EmitEventTreeNodeMoveTo(auto iAutoEventTreeNodeMoveTo, entity Entity, fromParentId, toParentId uid.Id) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventTreeNodeMoveTo()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventTreeNodeMoveTo](subscriber).OnTreeNodeMoveTo(entity, fromParentId, toParentId)
		return true
	})
}

func _EmitEventTreeNodeMoveToWithInterrupt(auto iAutoEventTreeNodeMoveTo, interrupt func(entity Entity, fromParentId, toParentId uid.Id) bool, entity Entity, fromParentId, toParentId uid.Id) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventTreeNodeMoveTo()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(entity, fromParentId, toParentId) {
				return false
			}
		}
		event.Cache2Iface[EventTreeNodeMoveTo](subscriber).OnTreeNodeMoveTo(entity, fromParentId, toParentId)
		return true
	})
}

func HandleEventTreeNodeMoveTo(fun func(entity Entity, fromParentId, toParentId uid.Id)) EventTreeNodeMoveToHandler {
	return EventTreeNodeMoveToHandler(fun)
}

type EventTreeNodeMoveToHandler func(entity Entity, fromParentId, toParentId uid.Id)

func (h EventTreeNodeMoveToHandler) OnTreeNodeMoveTo(entity Entity, fromParentId, toParentId uid.Id) {
	h(entity, fromParentId, toParentId)
}
