/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc eventtab --name=entityComponentManagerEventTab; DO NOT EDIT.

package ec

import (
	event "git.golaxy.org/core/event"
)

type IEntityComponentManagerEventTab interface {
	EventComponentManagerAddComponents() event.IEvent
	EventComponentManagerRemoveComponent() event.IEvent
	EventComponentManagerComponentEnableChanged() event.IEvent
	EventComponentManagerFirstTouchComponent() event.IEvent
}

var (
	_entityComponentManagerEventTabId = event.DeclareEventTabIdT[entityComponentManagerEventTab]()
	EventComponentManagerAddComponentsId = event.DeclareEventIdT[entityComponentManagerEventTab](0)
	EventComponentManagerRemoveComponentId = event.DeclareEventIdT[entityComponentManagerEventTab](1)
	EventComponentManagerComponentEnableChangedId = event.DeclareEventIdT[entityComponentManagerEventTab](2)
	EventComponentManagerFirstTouchComponentId = event.DeclareEventIdT[entityComponentManagerEventTab](3)
)

type entityComponentManagerEventTab [4]event.Event

func (eventTab *entityComponentManagerEventTab) SetPanicHandling(autoRecover bool, reportError chan error) {
	for i := range eventTab {
		eventTab[i].SetPanicHandling(autoRecover, reportError)
	}
}

func (eventTab *entityComponentManagerEventTab) SetRecursion(recursion event.EventRecursion) {
	eventTab[0].SetRecursion(event.EventRecursion_Allow)
	eventTab[1].SetRecursion(event.EventRecursion_Allow)
	eventTab[2].SetRecursion(event.EventRecursion_Allow)
	eventTab[3].SetRecursion(event.EventRecursion_Allow)
}

func (eventTab *entityComponentManagerEventTab) SetEnabled(b bool) {
	for i := range eventTab {
		eventTab[i].SetEnabled(b)
	}
}

func (eventTab *entityComponentManagerEventTab) UnbindAll() {
	for i := range eventTab {
		eventTab[i].UnbindAll()
	}
}

func (eventTab *entityComponentManagerEventTab) Ctrl() event.IEventCtrl {
	return eventTab
}

func (eventTab *entityComponentManagerEventTab) Event(id uint64) event.IEvent {
	eventTabId, pos := event.SplitEventId(id)
	if _entityComponentManagerEventTabId != eventTabId || pos >= len(eventTab) {
		return nil
	}
	switch pos {
	case 0:
		eventTab[0].SetRecursion(event.EventRecursion_Allow)
	case 1:
		eventTab[1].SetRecursion(event.EventRecursion_Allow)
	case 2:
		eventTab[2].SetRecursion(event.EventRecursion_Allow)
	case 3:
		eventTab[3].SetRecursion(event.EventRecursion_Allow)
	}
	return &eventTab[pos]
}

func (eventTab *entityComponentManagerEventTab) EventComponentManagerAddComponents() event.IEvent {
	eventTab.SetRecursion(event.EventRecursion_Allow)
	return &eventTab[0]
}

func (eventTab *entityComponentManagerEventTab) EventComponentManagerRemoveComponent() event.IEvent {
	eventTab.SetRecursion(event.EventRecursion_Allow)
	return &eventTab[1]
}

func (eventTab *entityComponentManagerEventTab) EventComponentManagerComponentEnableChanged() event.IEvent {
	eventTab.SetRecursion(event.EventRecursion_Allow)
	return &eventTab[2]
}

func (eventTab *entityComponentManagerEventTab) EventComponentManagerFirstTouchComponent() event.IEvent {
	eventTab.SetRecursion(event.EventRecursion_Allow)
	return &eventTab[3]
}
