// Code generated by "stringer -type EntityState"; DO NOT EDIT.

package ec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EntityState_Birth-0]
	_ = x[EntityState_Enter-1]
	_ = x[EntityState_Awake-2]
	_ = x[EntityState_Start-3]
	_ = x[EntityState_Alive-4]
	_ = x[EntityState_Leave-5]
	_ = x[EntityState_Shut-6]
	_ = x[EntityState_Death-7]
	_ = x[EntityState_Destroyed-8]
}

const _EntityState_name = "EntityState_BirthEntityState_EnterEntityState_AwakeEntityState_StartEntityState_AliveEntityState_LeaveEntityState_ShutEntityState_DeathEntityState_Destroyed"

var _EntityState_index = [...]uint8{0, 17, 34, 51, 68, 85, 102, 118, 135, 156}

func (i EntityState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EntityState_index)-1 {
		return "EntityState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntityState_name[_EntityState_index[idx]:_EntityState_index[idx+1]]
}
