// Code generated by eventcode --decl_file=entity_event.go gen_emit --package=demo_ec; DO NOT EDIT.

package ec

import (
	localevent "github.com/pangdogs/galaxy/localevent"
	"github.com/pangdogs/galaxy/util"
)

func emitEventEntityDestroySelf(event localevent.IEvent, entity Entity) {
	if event == nil {
		panic("nil event")
	}
	localevent.UnsafeEvent(event).Emit(func(delegate util.IfaceCache) bool {
		util.Cache2Iface[EventEntityDestroySelf](delegate).OnEntityDestroySelf(entity)
		return true
	})
}
