// Code generated by eventcode --decl_file=entity_treenode_event.go gen_event --package=ec; DO NOT EDIT.

package ec

import (
	"fmt"
	event "git.golaxy.org/core/event"
	iface "git.golaxy.org/core/util/iface"
)

type iAutoEventTreeNodeAddChild interface {
	EventTreeNodeAddChild() event.IEvent
}

func BindEventTreeNodeAddChild(auto iAutoEventTreeNodeAddChild, subscriber EventTreeNodeAddChild, priority ...int32) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.Bind[EventTreeNodeAddChild](auto.EventTreeNodeAddChild(), subscriber, priority...)
}

func _EmitEventTreeNodeAddChild(auto iAutoEventTreeNodeAddChild, parent, child Entity) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventTreeNodeAddChild()).Emit(func(subscriber iface.Cache) bool {
		iface.Cache2Iface[EventTreeNodeAddChild](subscriber).OnTreeNodeAddChild(parent, child)
		return true
	})
}

func _EmitEventTreeNodeAddChildWithInterrupt(auto iAutoEventTreeNodeAddChild, interrupt func(parent, child Entity) bool, parent, child Entity) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventTreeNodeAddChild()).Emit(func(subscriber iface.Cache) bool {
		if interrupt != nil {
			if interrupt(parent, child) {
				return false
			}
		}
		iface.Cache2Iface[EventTreeNodeAddChild](subscriber).OnTreeNodeAddChild(parent, child)
		return true
	})
}

func HandleEventTreeNodeAddChild(fun func(parent, child Entity)) EventTreeNodeAddChildHandler {
	return EventTreeNodeAddChildHandler(fun)
}

type EventTreeNodeAddChildHandler func(parent, child Entity)

func (h EventTreeNodeAddChildHandler) OnTreeNodeAddChild(parent, child Entity) {
	h(parent, child)
}

type iAutoEventTreeNodeRemoveChild interface {
	EventTreeNodeRemoveChild() event.IEvent
}

func BindEventTreeNodeRemoveChild(auto iAutoEventTreeNodeRemoveChild, subscriber EventTreeNodeRemoveChild, priority ...int32) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.Bind[EventTreeNodeRemoveChild](auto.EventTreeNodeRemoveChild(), subscriber, priority...)
}

func _EmitEventTreeNodeRemoveChild(auto iAutoEventTreeNodeRemoveChild, parent, child Entity) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventTreeNodeRemoveChild()).Emit(func(subscriber iface.Cache) bool {
		iface.Cache2Iface[EventTreeNodeRemoveChild](subscriber).OnTreeNodeRemoveChild(parent, child)
		return true
	})
}

func _EmitEventTreeNodeRemoveChildWithInterrupt(auto iAutoEventTreeNodeRemoveChild, interrupt func(parent, child Entity) bool, parent, child Entity) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventTreeNodeRemoveChild()).Emit(func(subscriber iface.Cache) bool {
		if interrupt != nil {
			if interrupt(parent, child) {
				return false
			}
		}
		iface.Cache2Iface[EventTreeNodeRemoveChild](subscriber).OnTreeNodeRemoveChild(parent, child)
		return true
	})
}

func HandleEventTreeNodeRemoveChild(fun func(parent, child Entity)) EventTreeNodeRemoveChildHandler {
	return EventTreeNodeRemoveChildHandler(fun)
}

type EventTreeNodeRemoveChildHandler func(parent, child Entity)

func (h EventTreeNodeRemoveChildHandler) OnTreeNodeRemoveChild(parent, child Entity) {
	h(parent, child)
}

type iAutoEventTreeNodeEnterParent interface {
	EventTreeNodeEnterParent() event.IEvent
}

func BindEventTreeNodeEnterParent(auto iAutoEventTreeNodeEnterParent, subscriber EventTreeNodeEnterParent, priority ...int32) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.Bind[EventTreeNodeEnterParent](auto.EventTreeNodeEnterParent(), subscriber, priority...)
}

func _EmitEventTreeNodeEnterParent(auto iAutoEventTreeNodeEnterParent, child, parent Entity) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventTreeNodeEnterParent()).Emit(func(subscriber iface.Cache) bool {
		iface.Cache2Iface[EventTreeNodeEnterParent](subscriber).OnTreeNodeEnterParent(child, parent)
		return true
	})
}

func _EmitEventTreeNodeEnterParentWithInterrupt(auto iAutoEventTreeNodeEnterParent, interrupt func(child, parent Entity) bool, child, parent Entity) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventTreeNodeEnterParent()).Emit(func(subscriber iface.Cache) bool {
		if interrupt != nil {
			if interrupt(child, parent) {
				return false
			}
		}
		iface.Cache2Iface[EventTreeNodeEnterParent](subscriber).OnTreeNodeEnterParent(child, parent)
		return true
	})
}

func HandleEventTreeNodeEnterParent(fun func(child, parent Entity)) EventTreeNodeEnterParentHandler {
	return EventTreeNodeEnterParentHandler(fun)
}

type EventTreeNodeEnterParentHandler func(child, parent Entity)

func (h EventTreeNodeEnterParentHandler) OnTreeNodeEnterParent(child, parent Entity) {
	h(child, parent)
}

type iAutoEventTreeNodeLeaveParent interface {
	EventTreeNodeLeaveParent() event.IEvent
}

func BindEventTreeNodeLeaveParent(auto iAutoEventTreeNodeLeaveParent, subscriber EventTreeNodeLeaveParent, priority ...int32) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.Bind[EventTreeNodeLeaveParent](auto.EventTreeNodeLeaveParent(), subscriber, priority...)
}

func _EmitEventTreeNodeLeaveParent(auto iAutoEventTreeNodeLeaveParent, child, parent Entity) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventTreeNodeLeaveParent()).Emit(func(subscriber iface.Cache) bool {
		iface.Cache2Iface[EventTreeNodeLeaveParent](subscriber).OnTreeNodeLeaveParent(child, parent)
		return true
	})
}

func _EmitEventTreeNodeLeaveParentWithInterrupt(auto iAutoEventTreeNodeLeaveParent, interrupt func(child, parent Entity) bool, child, parent Entity) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventTreeNodeLeaveParent()).Emit(func(subscriber iface.Cache) bool {
		if interrupt != nil {
			if interrupt(child, parent) {
				return false
			}
		}
		iface.Cache2Iface[EventTreeNodeLeaveParent](subscriber).OnTreeNodeLeaveParent(child, parent)
		return true
	})
}

func HandleEventTreeNodeLeaveParent(fun func(child, parent Entity)) EventTreeNodeLeaveParentHandler {
	return EventTreeNodeLeaveParentHandler(fun)
}

type EventTreeNodeLeaveParentHandler func(child, parent Entity)

func (h EventTreeNodeLeaveParentHandler) OnTreeNodeLeaveParent(child, parent Entity) {
	h(child, parent)
}
