// Code generated by "stringer -type EntityState"; DO NOT EDIT.

package ec

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EntityState_Born-0]
	_ = x[EntityState_Entered-1]
	_ = x[EntityState_Awaking-2]
	_ = x[EntityState_Starting-3]
	_ = x[EntityState_Alive-4]
	_ = x[EntityState_Leaving-5]
	_ = x[EntityState_Shutting-6]
	_ = x[EntityState_Dead-7]
	_ = x[EntityState_Destroyed-8]
}

const _EntityState_name = "EntityState_BornEntityState_EnteredEntityState_AwakingEntityState_StartingEntityState_AliveEntityState_LeavingEntityState_ShuttingEntityState_DeadEntityState_Destroyed"

var _EntityState_index = [...]uint8{0, 16, 35, 54, 74, 91, 110, 130, 146, 167}

func (i EntityState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_EntityState_index)-1 {
		return "EntityState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntityState_name[_EntityState_index[idx]:_EntityState_index[idx+1]]
}
