// Code generated by eventcode --decl_file=entity_componentmgr_event.go gen_emit --package=ec --default_auto=true; DO NOT EDIT.

package ec

import (
	"fmt"
	event "kit.golaxy.org/golaxy/event"
	iface "kit.golaxy.org/golaxy/util/iface"
)

type iAutoEventCompMgrAddComponents interface {
	EventCompMgrAddComponents() event.IEvent
}

func BindEventCompMgrAddComponents(auto iAutoEventCompMgrAddComponents, delegate EventCompMgrAddComponents, priority ...int32) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.BindEvent[EventCompMgrAddComponents](auto.EventCompMgrAddComponents(), delegate, priority...)
}

func emitEventCompMgrAddComponents(auto iAutoEventCompMgrAddComponents, entity Entity, components []Component) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventCompMgrAddComponents()).Emit(func(delegate iface.Cache) bool {
		iface.Cache2Iface[EventCompMgrAddComponents](delegate).OnCompMgrAddComponents(entity, components)
		return true
	})
}

type iAutoEventCompMgrRemoveComponent interface {
	EventCompMgrRemoveComponent() event.IEvent
}

func BindEventCompMgrRemoveComponent(auto iAutoEventCompMgrRemoveComponent, delegate EventCompMgrRemoveComponent, priority ...int32) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.BindEvent[EventCompMgrRemoveComponent](auto.EventCompMgrRemoveComponent(), delegate, priority...)
}

func emitEventCompMgrRemoveComponent(auto iAutoEventCompMgrRemoveComponent, entity Entity, component Component) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventCompMgrRemoveComponent()).Emit(func(delegate iface.Cache) bool {
		iface.Cache2Iface[EventCompMgrRemoveComponent](delegate).OnCompMgrRemoveComponent(entity, component)
		return true
	})
}

type iAutoEventCompMgrFirstAccessComponent interface {
	EventCompMgrFirstAccessComponent() event.IEvent
}

func BindEventCompMgrFirstAccessComponent(auto iAutoEventCompMgrFirstAccessComponent, delegate EventCompMgrFirstAccessComponent, priority ...int32) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.BindEvent[EventCompMgrFirstAccessComponent](auto.EventCompMgrFirstAccessComponent(), delegate, priority...)
}

func emitEventCompMgrFirstAccessComponent(auto iAutoEventCompMgrFirstAccessComponent, entity Entity, component Component) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventCompMgrFirstAccessComponent()).Emit(func(delegate iface.Cache) bool {
		iface.Cache2Iface[EventCompMgrFirstAccessComponent](delegate).OnCompMgrFirstAccessComponent(entity, component)
		return true
	})
}
