// Code generated by "stringer -type AddInState"; DO NOT EDIT.

package extension

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AddInState_Loaded-0]
	_ = x[AddInState_Running-1]
	_ = x[AddInState_Unloaded-2]
}

const _AddInState_name = "AddInState_LoadedAddInState_RunningAddInState_Unloaded"

var _AddInState_index = [...]uint8{0, 17, 35, 54}

func (i AddInState) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_AddInState_index)-1 {
		return "AddInState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AddInState_name[_AddInState_index[idx]:_AddInState_index[idx+1]]
}
