/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc event; DO NOT EDIT.

package extension

import (
	event "git.golaxy.org/core/event"
)

type iAutoEventRuntimeInstallAddIn interface {
	EventRuntimeInstallAddIn() event.IEvent
}

func BindEventRuntimeInstallAddIn(auto iAutoEventRuntimeInstallAddIn, subscriber EventRuntimeInstallAddIn, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventRuntimeInstallAddIn](auto.EventRuntimeInstallAddIn(), subscriber, priority...)
}

func _EmitEventRuntimeInstallAddIn(auto iAutoEventRuntimeInstallAddIn, status AddInStatus) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventRuntimeInstallAddIn()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventRuntimeInstallAddIn](subscriber).OnRuntimeInstallAddIn(status)
		return true
	})
}

func _EmitEventRuntimeInstallAddInWithInterrupt(auto iAutoEventRuntimeInstallAddIn, interrupt func(status AddInStatus) bool, status AddInStatus) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventRuntimeInstallAddIn()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(status) {
				return false
			}
		}
		event.Cache2Iface[EventRuntimeInstallAddIn](subscriber).OnRuntimeInstallAddIn(status)
		return true
	})
}

func HandleEventRuntimeInstallAddIn(fun func(status AddInStatus)) EventRuntimeInstallAddInHandler {
	return EventRuntimeInstallAddInHandler(fun)
}

type EventRuntimeInstallAddInHandler func(status AddInStatus)

func (h EventRuntimeInstallAddInHandler) OnRuntimeInstallAddIn(status AddInStatus) {
	h(status)
}

type iAutoEventRuntimeUninstallAddIn interface {
	EventRuntimeUninstallAddIn() event.IEvent
}

func BindEventRuntimeUninstallAddIn(auto iAutoEventRuntimeUninstallAddIn, subscriber EventRuntimeUninstallAddIn, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventRuntimeUninstallAddIn](auto.EventRuntimeUninstallAddIn(), subscriber, priority...)
}

func _EmitEventRuntimeUninstallAddIn(auto iAutoEventRuntimeUninstallAddIn, status AddInStatus) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventRuntimeUninstallAddIn()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventRuntimeUninstallAddIn](subscriber).OnRuntimeUninstallAddIn(status)
		return true
	})
}

func _EmitEventRuntimeUninstallAddInWithInterrupt(auto iAutoEventRuntimeUninstallAddIn, interrupt func(status AddInStatus) bool, status AddInStatus) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventRuntimeUninstallAddIn()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(status) {
				return false
			}
		}
		event.Cache2Iface[EventRuntimeUninstallAddIn](subscriber).OnRuntimeUninstallAddIn(status)
		return true
	})
}

func HandleEventRuntimeUninstallAddIn(fun func(status AddInStatus)) EventRuntimeUninstallAddInHandler {
	return EventRuntimeUninstallAddInHandler(fun)
}

type EventRuntimeUninstallAddInHandler func(status AddInStatus)

func (h EventRuntimeUninstallAddInHandler) OnRuntimeUninstallAddIn(status AddInStatus) {
	h(status)
}

type iAutoEventRuntimeAddInStateChanged interface {
	EventRuntimeAddInStateChanged() event.IEvent
}

func BindEventRuntimeAddInStateChanged(auto iAutoEventRuntimeAddInStateChanged, subscriber EventRuntimeAddInStateChanged, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventRuntimeAddInStateChanged](auto.EventRuntimeAddInStateChanged(), subscriber, priority...)
}

func _EmitEventRuntimeAddInStateChanged(auto iAutoEventRuntimeAddInStateChanged, status AddInStatus, state AddInState) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventRuntimeAddInStateChanged()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventRuntimeAddInStateChanged](subscriber).OnRuntimeAddInStateChanged(status, state)
		return true
	})
}

func _EmitEventRuntimeAddInStateChangedWithInterrupt(auto iAutoEventRuntimeAddInStateChanged, interrupt func(status AddInStatus, state AddInState) bool, status AddInStatus, state AddInState) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventRuntimeAddInStateChanged()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(status, state) {
				return false
			}
		}
		event.Cache2Iface[EventRuntimeAddInStateChanged](subscriber).OnRuntimeAddInStateChanged(status, state)
		return true
	})
}

func HandleEventRuntimeAddInStateChanged(fun func(status AddInStatus, state AddInState)) EventRuntimeAddInStateChangedHandler {
	return EventRuntimeAddInStateChangedHandler(fun)
}

type EventRuntimeAddInStateChangedHandler func(status AddInStatus, state AddInState)

func (h EventRuntimeAddInStateChangedHandler) OnRuntimeAddInStateChanged(status AddInStatus, state AddInState) {
	h(status, state)
}
