// Code generated by eventcode --decl_file=runtime_event.go gen_event --package=golaxy --default_export=false --default_auto=false; DO NOT EDIT.

package golaxy

import (
	"fmt"
	event "kit.golaxy.org/golaxy/event"
	iface "kit.golaxy.org/golaxy/util/iface"
)

func emitEventUpdate(evt event.IEvent) {
	if evt == nil {
		panic(fmt.Errorf("%w: %w: evt is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(evt).Emit(func(subscriber iface.Cache) bool {
		iface.Cache2Iface[eventUpdate](subscriber).Update()
		return true
	})
}

func emitEventLateUpdate(evt event.IEvent) {
	if evt == nil {
		panic(fmt.Errorf("%w: %w: evt is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(evt).Emit(func(subscriber iface.Cache) bool {
		iface.Cache2Iface[eventLateUpdate](subscriber).LateUpdate()
		return true
	})
}
