/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc eventtab --name=runtimeEventTab --export_interface=false; DO NOT EDIT.

package core

import (
	event "git.golaxy.org/core/event"
)

type iRuntimeEventTab interface {
	eventUpdate() event.IEvent
	eventLateUpdate() event.IEvent
}

var (
	_runtimeEventTabId = event.DeclareEventTabIdT[runtimeEventTab]()
	eventUpdateId = _runtimeEventTabId + 0
	eventLateUpdateId = _runtimeEventTabId + 1
)

type runtimeEventTab [2]event.Event

func (eventTab *runtimeEventTab) SetPanicHandling(autoRecover bool, reportError chan error) {
	for i := range *eventTab {
		(*eventTab)[i].SetPanicHandling(autoRecover, reportError)
	}
}

func (eventTab *runtimeEventTab) SetRecursion(recursion event.EventRecursion) {
	(*eventTab)[0].SetRecursion(event.EventRecursion_Disallow)
	(*eventTab)[1].SetRecursion(event.EventRecursion_Disallow)
}

func (eventTab *runtimeEventTab) SetEnabled(b bool) {
	for i := range *eventTab {
		(*eventTab)[i].SetEnabled(b)
	}
}

func (eventTab *runtimeEventTab) UnbindAll() {
	for i := range *eventTab {
		(*eventTab)[i].UnbindAll()
	}
}

func (eventTab *runtimeEventTab) Ctrl() event.IEventCtrl {
	return eventTab
}

func (eventTab *runtimeEventTab) Event(id uint64) event.IEvent {
	if _runtimeEventTabId != id & 0xFFFFFFFF00000000 {
		return nil
	}
	pos := id & 0xFFFFFFFF
	if pos >= uint64(len(*eventTab)) {
		return nil
	}
	switch pos {
	case 0:
		(*eventTab)[0].SetRecursion(event.EventRecursion_Disallow)
	case 1:
		(*eventTab)[1].SetRecursion(event.EventRecursion_Disallow)
	}
	return &(*eventTab)[pos]
}

func (eventTab *runtimeEventTab) eventUpdate() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Disallow)
	return &(*eventTab)[0]
}

func (eventTab *runtimeEventTab) eventLateUpdate() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Disallow)
	return &(*eventTab)[1]
}
