// Code generated by eventcode --decl_file=runtime_event.go gen_event --package=core --default_export=false --default_auto=false; DO NOT EDIT.

package core

import (
	"fmt"
	event "git.golaxy.org/core/event"
	iface "git.golaxy.org/core/util/iface"
)

func emitEventUpdate(evt event.IEvent) {
	if evt == nil {
		panic(fmt.Errorf("%w: %w: evt is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(evt).Emit(func(subscriber iface.Cache) bool {
		iface.Cache2Iface[eventUpdate](subscriber).Update()
		return true
	})
}

func _HandleEventUpdate(fun func()) handleEventUpdate {
	return handleEventUpdate(fun)
}

type handleEventUpdate func()

func (handle handleEventUpdate) Update() {
	handle()
}

func emitEventLateUpdate(evt event.IEvent) {
	if evt == nil {
		panic(fmt.Errorf("%w: %w: evt is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(evt).Emit(func(subscriber iface.Cache) bool {
		iface.Cache2Iface[eventLateUpdate](subscriber).LateUpdate()
		return true
	})
}

func _HandleEventLateUpdate(fun func()) handleEventLateUpdate {
	return handleEventLateUpdate(fun)
}

type handleEventLateUpdate func()

func (handle handleEventLateUpdate) LateUpdate() {
	handle()
}
