/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc event; DO NOT EDIT.

package core

import (
	event "git.golaxy.org/core/event"
)

type iAutoEventUpdate interface {
	eventUpdate() event.IEvent
}

func _BindEventUpdate(auto iAutoEventUpdate, subscriber eventUpdate, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[eventUpdate](auto.eventUpdate(), subscriber, priority...)
}

func _EmitEventUpdate(auto iAutoEventUpdate) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.eventUpdate()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[eventUpdate](subscriber).Update()
		return true
	})
}

func _EmitEventUpdateWithInterrupt(auto iAutoEventUpdate, interrupt func() bool) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.eventUpdate()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt() {
				return false
			}
		}
		event.Cache2Iface[eventUpdate](subscriber).Update()
		return true
	})
}

func _HandleEventUpdate(fun func()) _EventUpdateHandler {
	return _EventUpdateHandler(fun)
}

type _EventUpdateHandler func()

func (h _EventUpdateHandler) Update() {
	h()
}

type iAutoEventLateUpdate interface {
	eventLateUpdate() event.IEvent
}

func _BindEventLateUpdate(auto iAutoEventLateUpdate, subscriber eventLateUpdate, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[eventLateUpdate](auto.eventLateUpdate(), subscriber, priority...)
}

func _EmitEventLateUpdate(auto iAutoEventLateUpdate) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.eventLateUpdate()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[eventLateUpdate](subscriber).LateUpdate()
		return true
	})
}

func _EmitEventLateUpdateWithInterrupt(auto iAutoEventLateUpdate, interrupt func() bool) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.eventLateUpdate()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt() {
				return false
			}
		}
		event.Cache2Iface[eventLateUpdate](subscriber).LateUpdate()
		return true
	})
}

func _HandleEventLateUpdate(fun func()) _EventLateUpdateHandler {
	return _EventLateUpdateHandler(fun)
}

type _EventLateUpdateHandler func()

func (h _EventLateUpdateHandler) LateUpdate() {
	h()
}
