/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc event; DO NOT EDIT.

package runtime

import (
	event "git.golaxy.org/core/event"
	"git.golaxy.org/core/extension"
)

type iAutoEventInstallAddIn interface {
	EventInstallAddIn() event.IEvent
}

func BindEventInstallAddIn(auto iAutoEventInstallAddIn, subscriber EventInstallAddIn, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventInstallAddIn](auto.EventInstallAddIn(), subscriber, priority...)
}

func _EmitEventInstallAddIn(auto iAutoEventInstallAddIn, status AddInStatus) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventInstallAddIn()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventInstallAddIn](subscriber).OnInstallAddIn(status)
		return true
	})
}

func _EmitEventInstallAddInWithInterrupt(auto iAutoEventInstallAddIn, interrupt func(status AddInStatus) bool, status AddInStatus) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventInstallAddIn()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(status) {
				return false
			}
		}
		event.Cache2Iface[EventInstallAddIn](subscriber).OnInstallAddIn(status)
		return true
	})
}

func HandleEventInstallAddIn(fun func(status AddInStatus)) EventInstallAddInHandler {
	return EventInstallAddInHandler(fun)
}

type EventInstallAddInHandler func(status AddInStatus)

func (h EventInstallAddInHandler) OnInstallAddIn(status AddInStatus) {
	h(status)
}

type iAutoEventUninstallAddIn interface {
	EventUninstallAddIn() event.IEvent
}

func BindEventUninstallAddIn(auto iAutoEventUninstallAddIn, subscriber EventUninstallAddIn, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventUninstallAddIn](auto.EventUninstallAddIn(), subscriber, priority...)
}

func _EmitEventUninstallAddIn(auto iAutoEventUninstallAddIn, status AddInStatus) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventUninstallAddIn()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventUninstallAddIn](subscriber).OnUninstallAddIn(status)
		return true
	})
}

func _EmitEventUninstallAddInWithInterrupt(auto iAutoEventUninstallAddIn, interrupt func(status AddInStatus) bool, status AddInStatus) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventUninstallAddIn()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(status) {
				return false
			}
		}
		event.Cache2Iface[EventUninstallAddIn](subscriber).OnUninstallAddIn(status)
		return true
	})
}

func HandleEventUninstallAddIn(fun func(status AddInStatus)) EventUninstallAddInHandler {
	return EventUninstallAddInHandler(fun)
}

type EventUninstallAddInHandler func(status AddInStatus)

func (h EventUninstallAddInHandler) OnUninstallAddIn(status AddInStatus) {
	h(status)
}

type iAutoEventAddInStateChanged interface {
	EventAddInStateChanged() event.IEvent
}

func BindEventAddInStateChanged(auto iAutoEventAddInStateChanged, subscriber EventAddInStateChanged, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventAddInStateChanged](auto.EventAddInStateChanged(), subscriber, priority...)
}

func _EmitEventAddInStateChanged(auto iAutoEventAddInStateChanged, status AddInStatus, state extension.AddInState) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventAddInStateChanged()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventAddInStateChanged](subscriber).OnAddInStateChanged(status, state)
		return true
	})
}

func _EmitEventAddInStateChangedWithInterrupt(auto iAutoEventAddInStateChanged, interrupt func(status AddInStatus, state extension.AddInState) bool, status AddInStatus, state extension.AddInState) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventAddInStateChanged()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(status, state) {
				return false
			}
		}
		event.Cache2Iface[EventAddInStateChanged](subscriber).OnAddInStateChanged(status, state)
		return true
	})
}

func HandleEventAddInStateChanged(fun func(status AddInStatus, state extension.AddInState)) EventAddInStateChangedHandler {
	return EventAddInStateChangedHandler(fun)
}

type EventAddInStateChangedHandler func(status AddInStatus, state extension.AddInState)

func (h EventAddInStateChangedHandler) OnAddInStateChanged(status AddInStatus, state extension.AddInState) {
	h(status, state)
}
