/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc event; DO NOT EDIT.

package runtime

import (
	event "git.golaxy.org/core/event"
)

type iAutoEventContextRunningEvent interface {
	EventContextRunningEvent() event.IEvent
}

func BindEventContextRunningEvent(auto iAutoEventContextRunningEvent, subscriber EventContextRunningEvent, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventContextRunningEvent](auto.EventContextRunningEvent(), subscriber, priority...)
}

func _EmitEventContextRunningEvent(auto iAutoEventContextRunningEvent, ctx Context, runningEvent RunningEvent, args ...any) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventContextRunningEvent()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventContextRunningEvent](subscriber).OnContextRunningEvent(ctx, runningEvent, args...)
		return true
	})
}

func _EmitEventContextRunningEventWithInterrupt(auto iAutoEventContextRunningEvent, interrupt func(ctx Context, runningEvent RunningEvent, args ...any) bool, ctx Context, runningEvent RunningEvent, args ...any) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventContextRunningEvent()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(ctx, runningEvent, args...) {
				return false
			}
		}
		event.Cache2Iface[EventContextRunningEvent](subscriber).OnContextRunningEvent(ctx, runningEvent, args...)
		return true
	})
}

func HandleEventContextRunningEvent(fun func(ctx Context, runningEvent RunningEvent, args ...any)) EventContextRunningEventHandler {
	return EventContextRunningEventHandler(fun)
}

type EventContextRunningEventHandler func(ctx Context, runningEvent RunningEvent, args ...any)

func (h EventContextRunningEventHandler) OnContextRunningEvent(ctx Context, runningEvent RunningEvent, args ...any) {
	h(ctx, runningEvent, args...)
}
