// Code generated by eventcode --decl_file=ectree_event.go gen_event --package=runtime; DO NOT EDIT.

package runtime

import (
	"fmt"
	event "kit.golaxy.org/golaxy/event"
	iface "kit.golaxy.org/golaxy/util/iface"
	"kit.golaxy.org/golaxy/ec"
)

type iAutoEventECTreeAddChild interface {
	EventECTreeAddChild() event.IEvent
}

func BindEventECTreeAddChild(auto iAutoEventECTreeAddChild, subscriber EventECTreeAddChild, priority ...int32) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.BindEvent[EventECTreeAddChild](auto.EventECTreeAddChild(), subscriber, priority...)
}

func emitEventECTreeAddChild(auto iAutoEventECTreeAddChild, ecTree ECTree, parent, child ec.Entity) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventECTreeAddChild()).Emit(func(subscriber iface.Cache) bool {
		iface.Cache2Iface[EventECTreeAddChild](subscriber).OnAddChild(ecTree, parent, child)
		return true
	})
}

type iAutoEventECTreeRemoveChild interface {
	EventECTreeRemoveChild() event.IEvent
}

func BindEventECTreeRemoveChild(auto iAutoEventECTreeRemoveChild, subscriber EventECTreeRemoveChild, priority ...int32) event.Hook {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	return event.BindEvent[EventECTreeRemoveChild](auto.EventECTreeRemoveChild(), subscriber, priority...)
}

func emitEventECTreeRemoveChild(auto iAutoEventECTreeRemoveChild, ecTree ECTree, parent, child ec.Entity) {
	if auto == nil {
		panic(fmt.Errorf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs))
	}
	event.UnsafeEvent(auto.EventECTreeRemoveChild()).Emit(func(subscriber iface.Cache) bool {
		iface.Cache2Iface[EventECTreeRemoveChild](subscriber).OnRemoveChild(ecTree, parent, child)
		return true
	})
}
