/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc eventtab --name=entityManagerEventTab; DO NOT EDIT.

package runtime

import (
	event "git.golaxy.org/core/event"
)

type IEntityManagerEventTab interface {
	EventEntityManagerAddEntity() event.IEvent
	EventEntityManagerRemoveEntity() event.IEvent
	EventEntityManagerEntityAddComponents() event.IEvent
	EventEntityManagerEntityRemoveComponent() event.IEvent
	EventEntityManagerEntityComponentEnableChanged() event.IEvent
	EventEntityManagerEntityFirstTouchComponent() event.IEvent
}

var (
	_entityManagerEventTabId = event.DeclareEventTabIdT[entityManagerEventTab]()
	EventEntityManagerAddEntityId = _entityManagerEventTabId + 0
	EventEntityManagerRemoveEntityId = _entityManagerEventTabId + 1
	EventEntityManagerEntityAddComponentsId = _entityManagerEventTabId + 2
	EventEntityManagerEntityRemoveComponentId = _entityManagerEventTabId + 3
	EventEntityManagerEntityComponentEnableChangedId = _entityManagerEventTabId + 4
	EventEntityManagerEntityFirstTouchComponentId = _entityManagerEventTabId + 5
)

type entityManagerEventTab [6]event.Event

func (eventTab *entityManagerEventTab) SetPanicHandling(autoRecover bool, reportError chan error) {
	for i := range *eventTab {
		(*eventTab)[i].SetPanicHandling(autoRecover, reportError)
	}
}

func (eventTab *entityManagerEventTab) SetRecursion(recursion event.EventRecursion) {
	(*eventTab)[0].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[1].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[2].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[3].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[4].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[5].SetRecursion(event.EventRecursion_Allow)
}

func (eventTab *entityManagerEventTab) SetEnabled(b bool) {
	for i := range *eventTab {
		(*eventTab)[i].SetEnabled(b)
	}
}

func (eventTab *entityManagerEventTab) UnbindAll() {
	for i := range *eventTab {
		(*eventTab)[i].UnbindAll()
	}
}

func (eventTab *entityManagerEventTab) Ctrl() event.IEventCtrl {
	return eventTab
}

func (eventTab *entityManagerEventTab) Event(id uint64) event.IEvent {
	if _entityManagerEventTabId != id & 0xFFFFFFFF00000000 {
		return nil
	}
	pos := id & 0xFFFFFFFF
	if pos >= uint64(len(*eventTab)) {
		return nil
	}
	switch pos {
	case 0:
		(*eventTab)[0].SetRecursion(event.EventRecursion_Allow)
	case 1:
		(*eventTab)[1].SetRecursion(event.EventRecursion_Allow)
	case 2:
		(*eventTab)[2].SetRecursion(event.EventRecursion_Allow)
	case 3:
		(*eventTab)[3].SetRecursion(event.EventRecursion_Allow)
	case 4:
		(*eventTab)[4].SetRecursion(event.EventRecursion_Allow)
	case 5:
		(*eventTab)[5].SetRecursion(event.EventRecursion_Allow)
	}
	return &(*eventTab)[pos]
}

func (eventTab *entityManagerEventTab) EventEntityManagerAddEntity() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[0]
}

func (eventTab *entityManagerEventTab) EventEntityManagerRemoveEntity() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[1]
}

func (eventTab *entityManagerEventTab) EventEntityManagerEntityAddComponents() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[2]
}

func (eventTab *entityManagerEventTab) EventEntityManagerEntityRemoveComponent() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[3]
}

func (eventTab *entityManagerEventTab) EventEntityManagerEntityComponentEnableChanged() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[4]
}

func (eventTab *entityManagerEventTab) EventEntityManagerEntityFirstTouchComponent() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[5]
}
