/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc event; DO NOT EDIT.

package runtime

import (
	event "git.golaxy.org/core/event"
	"git.golaxy.org/core/utils/uid"
)

type iAutoEventEntityTreeAddNode interface {
	EventEntityTreeAddNode() event.IEvent
}

func BindEventEntityTreeAddNode(auto iAutoEventEntityTreeAddNode, subscriber EventEntityTreeAddNode, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventEntityTreeAddNode](auto.EventEntityTreeAddNode(), subscriber, priority...)
}

func _EmitEventEntityTreeAddNode(auto iAutoEventEntityTreeAddNode, entityTree EntityTree, parentID, childID uid.ID) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventEntityTreeAddNode()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventEntityTreeAddNode](subscriber).OnEntityTreeAddNode(entityTree, parentID, childID)
		return true
	})
}

func _EmitEventEntityTreeAddNodeWithInterrupt(auto iAutoEventEntityTreeAddNode, interrupt func(entityTree EntityTree, parentID, childID uid.ID) bool, entityTree EntityTree, parentID, childID uid.ID) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventEntityTreeAddNode()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(entityTree, parentID, childID) {
				return false
			}
		}
		event.Cache2Iface[EventEntityTreeAddNode](subscriber).OnEntityTreeAddNode(entityTree, parentID, childID)
		return true
	})
}

func HandleEventEntityTreeAddNode(fun func(entityTree EntityTree, parentID, childID uid.ID)) EventEntityTreeAddNodeHandler {
	return EventEntityTreeAddNodeHandler(fun)
}

type EventEntityTreeAddNodeHandler func(entityTree EntityTree, parentID, childID uid.ID)

func (h EventEntityTreeAddNodeHandler) OnEntityTreeAddNode(entityTree EntityTree, parentID, childID uid.ID) {
	h(entityTree, parentID, childID)
}

type iAutoEventEntityTreeRemoveNode interface {
	EventEntityTreeRemoveNode() event.IEvent
}

func BindEventEntityTreeRemoveNode(auto iAutoEventEntityTreeRemoveNode, subscriber EventEntityTreeRemoveNode, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventEntityTreeRemoveNode](auto.EventEntityTreeRemoveNode(), subscriber, priority...)
}

func _EmitEventEntityTreeRemoveNode(auto iAutoEventEntityTreeRemoveNode, entityTree EntityTree, parentID, childID uid.ID) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventEntityTreeRemoveNode()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventEntityTreeRemoveNode](subscriber).OnEntityTreeRemoveNode(entityTree, parentID, childID)
		return true
	})
}

func _EmitEventEntityTreeRemoveNodeWithInterrupt(auto iAutoEventEntityTreeRemoveNode, interrupt func(entityTree EntityTree, parentID, childID uid.ID) bool, entityTree EntityTree, parentID, childID uid.ID) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventEntityTreeRemoveNode()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(entityTree, parentID, childID) {
				return false
			}
		}
		event.Cache2Iface[EventEntityTreeRemoveNode](subscriber).OnEntityTreeRemoveNode(entityTree, parentID, childID)
		return true
	})
}

func HandleEventEntityTreeRemoveNode(fun func(entityTree EntityTree, parentID, childID uid.ID)) EventEntityTreeRemoveNodeHandler {
	return EventEntityTreeRemoveNodeHandler(fun)
}

type EventEntityTreeRemoveNodeHandler func(entityTree EntityTree, parentID, childID uid.ID)

func (h EventEntityTreeRemoveNodeHandler) OnEntityTreeRemoveNode(entityTree EntityTree, parentID, childID uid.ID) {
	h(entityTree, parentID, childID)
}

type iAutoEventEntityTreeMoveNode interface {
	EventEntityTreeMoveNode() event.IEvent
}

func BindEventEntityTreeMoveNode(auto iAutoEventEntityTreeMoveNode, subscriber EventEntityTreeMoveNode, priority ...int32) event.Handle {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	return event.Bind[EventEntityTreeMoveNode](auto.EventEntityTreeMoveNode(), subscriber, priority...)
}

func _EmitEventEntityTreeMoveNode(auto iAutoEventEntityTreeMoveNode, entityTree EntityTree, childID, fromParentID, toParentID uid.ID) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventEntityTreeMoveNode()).Emit(func(subscriber event.Cache) bool {
		event.Cache2Iface[EventEntityTreeMoveNode](subscriber).OnEntityTreeMoveNode(entityTree, childID, fromParentID, toParentID)
		return true
	})
}

func _EmitEventEntityTreeMoveNodeWithInterrupt(auto iAutoEventEntityTreeMoveNode, interrupt func(entityTree EntityTree, childID, fromParentID, toParentID uid.ID) bool, entityTree EntityTree, childID, fromParentID, toParentID uid.ID) {
	if auto == nil {
		event.Panicf("%w: %w: auto is nil", event.ErrEvent, event.ErrArgs)
	}
	event.UnsafeEvent(auto.EventEntityTreeMoveNode()).Emit(func(subscriber event.Cache) bool {
		if interrupt != nil {
			if interrupt(entityTree, childID, fromParentID, toParentID) {
				return false
			}
		}
		event.Cache2Iface[EventEntityTreeMoveNode](subscriber).OnEntityTreeMoveNode(entityTree, childID, fromParentID, toParentID)
		return true
	})
}

func HandleEventEntityTreeMoveNode(fun func(entityTree EntityTree, childID, fromParentID, toParentID uid.ID)) EventEntityTreeMoveNodeHandler {
	return EventEntityTreeMoveNodeHandler(fun)
}

type EventEntityTreeMoveNodeHandler func(entityTree EntityTree, childID, fromParentID, toParentID uid.ID)

func (h EventEntityTreeMoveNodeHandler) OnEntityTreeMoveNode(entityTree EntityTree, childID, fromParentID, toParentID uid.ID) {
	h(entityTree, childID, fromParentID, toParentID)
}
