/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc eventtab --name=entityManagerEventTab; DO NOT EDIT.

package runtime

import (
	event "git.golaxy.org/core/event"
)

type IEntityManagerEventTab interface {
	EventEntityManagerAddEntity() event.IEvent
	EventEntityManagerRemoveEntity() event.IEvent
	EventEntityManagerEntityAddComponents() event.IEvent
	EventEntityManagerEntityRemoveComponent() event.IEvent
	EventEntityManagerEntityFirstTouchComponent() event.IEvent
}

var (
	_entityManagerEventTabId = event.DeclareEventTabIdT[entityManagerEventTab]()
	EventEntityManagerAddEntityId = _entityManagerEventTabId + 0
	EventEntityManagerRemoveEntityId = _entityManagerEventTabId + 1
	EventEntityManagerEntityAddComponentsId = _entityManagerEventTabId + 2
	EventEntityManagerEntityRemoveComponentId = _entityManagerEventTabId + 3
	EventEntityManagerEntityFirstTouchComponentId = _entityManagerEventTabId + 4
)

type entityManagerEventTab [5]event.Event

func (eventTab *entityManagerEventTab) Init(autoRecover bool, reportError chan error, recursion event.EventRecursion) {
	(*eventTab)[0].Init(autoRecover, reportError, recursion)
	(*eventTab)[1].Init(autoRecover, reportError, recursion)
	(*eventTab)[2].Init(autoRecover, reportError, recursion)
	(*eventTab)[3].Init(autoRecover, reportError, recursion)
	(*eventTab)[4].Init(autoRecover, reportError, recursion)
}

func (eventTab *entityManagerEventTab) Enable() {
	for i := range *eventTab {
		(*eventTab)[i].Enable()
	}
}

func (eventTab *entityManagerEventTab) Disable() {
	for i := range *eventTab {
		(*eventTab)[i].Disable()
	}
}

func (eventTab *entityManagerEventTab) UnbindAll() {
	for i := range *eventTab {
		(*eventTab)[i].UnbindAll()
	}
}

func (eventTab *entityManagerEventTab) Ctrl() event.IEventCtrl {
	return eventTab
}

func (eventTab *entityManagerEventTab) Event(id uint64) event.IEvent {
	if _entityManagerEventTabId != id & 0xFFFFFFFF00000000 {
		return nil
	}
	pos := id & 0xFFFFFFFF
	if pos >= uint64(len(*eventTab)) {
		return nil
	}
	return &(*eventTab)[pos]
}

func (eventTab *entityManagerEventTab) EventEntityManagerAddEntity() event.IEvent {
	return &(*eventTab)[0]
}

func (eventTab *entityManagerEventTab) EventEntityManagerRemoveEntity() event.IEvent {
	return &(*eventTab)[1]
}

func (eventTab *entityManagerEventTab) EventEntityManagerEntityAddComponents() event.IEvent {
	return &(*eventTab)[2]
}

func (eventTab *entityManagerEventTab) EventEntityManagerEntityRemoveComponent() event.IEvent {
	return &(*eventTab)[3]
}

func (eventTab *entityManagerEventTab) EventEntityManagerEntityFirstTouchComponent() event.IEvent {
	return &(*eventTab)[4]
}
