/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */

// Code generated by eventc eventtab --name=entityTreeEventTab; DO NOT EDIT.

package runtime

import (
	event "git.golaxy.org/core/event"
)

type IEntityTreeEventTab interface {
	EventEntityTreeAddNode() event.IEvent
	EventEntityTreeRemoveNode() event.IEvent
	EventEntityTreeMoveNode() event.IEvent
}

var (
	_entityTreeEventTabId = event.DeclareEventTabIdT[entityTreeEventTab]()
	EventEntityTreeAddNodeId = _entityTreeEventTabId + 0
	EventEntityTreeRemoveNodeId = _entityTreeEventTabId + 1
	EventEntityTreeMoveNodeId = _entityTreeEventTabId + 2
)

type entityTreeEventTab [3]event.Event

func (eventTab *entityTreeEventTab) SetPanicHandling(autoRecover bool, reportError chan error) {
	for i := range *eventTab {
		(*eventTab)[i].SetPanicHandling(autoRecover, reportError)
	}
}

func (eventTab *entityTreeEventTab) SetRecursion(recursion event.EventRecursion) {
	(*eventTab)[0].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[1].SetRecursion(event.EventRecursion_Allow)
	(*eventTab)[2].SetRecursion(event.EventRecursion_Allow)
}

func (eventTab *entityTreeEventTab) SetEnabled(b bool) {
	for i := range *eventTab {
		(*eventTab)[i].SetEnabled(b)
	}
}

func (eventTab *entityTreeEventTab) UnbindAll() {
	for i := range *eventTab {
		(*eventTab)[i].UnbindAll()
	}
}

func (eventTab *entityTreeEventTab) Ctrl() event.IEventCtrl {
	return eventTab
}

func (eventTab *entityTreeEventTab) Event(id uint64) event.IEvent {
	if _entityTreeEventTabId != id & 0xFFFFFFFF00000000 {
		return nil
	}
	pos := id & 0xFFFFFFFF
	if pos >= uint64(len(*eventTab)) {
		return nil
	}
	switch pos {
	case 0:
		(*eventTab)[0].SetRecursion(event.EventRecursion_Allow)
	case 1:
		(*eventTab)[1].SetRecursion(event.EventRecursion_Allow)
	case 2:
		(*eventTab)[2].SetRecursion(event.EventRecursion_Allow)
	}
	return &(*eventTab)[pos]
}

func (eventTab *entityTreeEventTab) EventEntityTreeAddNode() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[0]
}

func (eventTab *entityTreeEventTab) EventEntityTreeRemoveNode() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[1]
}

func (eventTab *entityTreeEventTab) EventEntityTreeMoveNode() event.IEvent {
	(*eventTab).SetRecursion(event.EventRecursion_Allow)
	return &(*eventTab)[2]
}
