// Code generated by "stringer -type RunningEvent"; DO NOT EDIT.

package runtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RunningEvent_Birth-0]
	_ = x[RunningEvent_Starting-1]
	_ = x[RunningEvent_Started-2]
	_ = x[RunningEvent_FrameLoopBegin-3]
	_ = x[RunningEvent_FrameUpdateBegin-4]
	_ = x[RunningEvent_FrameUpdateEnd-5]
	_ = x[RunningEvent_FrameLoopEnd-6]
	_ = x[RunningEvent_RunCallBegin-7]
	_ = x[RunningEvent_RunCallEnd-8]
	_ = x[RunningEvent_RunGCBegin-9]
	_ = x[RunningEvent_RunGCEnd-10]
	_ = x[RunningEvent_Terminating-11]
	_ = x[RunningEvent_Terminated-12]
	_ = x[RunningEvent_AddInActivating-13]
	_ = x[RunningEvent_AddInActivatingAborted-14]
	_ = x[RunningEvent_AddInActivatingDone-15]
	_ = x[RunningEvent_AddInDeactivating-16]
	_ = x[RunningEvent_AddInDeactivatingDone-17]
	_ = x[RunningEvent_EntityActivating-18]
	_ = x[RunningEvent_EntityActivatingAborted-19]
	_ = x[RunningEvent_EntityActivatingDone-20]
	_ = x[RunningEvent_EntityDeactivating-21]
	_ = x[RunningEvent_EntityDeactivatingDone-22]
	_ = x[RunningEvent_EntityAddingComponents-23]
	_ = x[RunningEvent_EntityAddingComponentsAborted-24]
	_ = x[RunningEvent_EntityAddingComponentsDone-25]
	_ = x[RunningEvent_EntityRemovingComponent-26]
	_ = x[RunningEvent_EntityRemovingComponentAborted-27]
	_ = x[RunningEvent_EntityRemovingComponentDone-28]
}

const _RunningEvent_name = "RunningEvent_BirthRunningEvent_StartingRunningEvent_StartedRunningEvent_FrameLoopBeginRunningEvent_FrameUpdateBeginRunningEvent_FrameUpdateEndRunningEvent_FrameLoopEndRunningEvent_RunCallBeginRunningEvent_RunCallEndRunningEvent_RunGCBeginRunningEvent_RunGCEndRunningEvent_TerminatingRunningEvent_TerminatedRunningEvent_AddInActivatingRunningEvent_AddInActivatingAbortedRunningEvent_AddInActivatingDoneRunningEvent_AddInDeactivatingRunningEvent_AddInDeactivatingDoneRunningEvent_EntityActivatingRunningEvent_EntityActivatingAbortedRunningEvent_EntityActivatingDoneRunningEvent_EntityDeactivatingRunningEvent_EntityDeactivatingDoneRunningEvent_EntityAddingComponentsRunningEvent_EntityAddingComponentsAbortedRunningEvent_EntityAddingComponentsDoneRunningEvent_EntityRemovingComponentRunningEvent_EntityRemovingComponentAbortedRunningEvent_EntityRemovingComponentDone"

var _RunningEvent_index = [...]uint16{0, 18, 39, 59, 86, 115, 142, 167, 192, 215, 238, 259, 283, 306, 334, 369, 401, 431, 465, 494, 530, 563, 594, 629, 664, 706, 745, 781, 824, 864}

func (i RunningEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RunningEvent_index)-1 {
		return "RunningEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunningEvent_name[_RunningEvent_index[idx]:_RunningEvent_index[idx+1]]
}
