// Code generated by "stringer -type RunningState"; DO NOT EDIT.

package runtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RunningState_Birth-0]
	_ = x[RunningState_Starting-1]
	_ = x[RunningState_Started-2]
	_ = x[RunningState_FrameLoopBegin-3]
	_ = x[RunningState_FrameUpdateBegin-4]
	_ = x[RunningState_FrameUpdateEnd-5]
	_ = x[RunningState_FrameLoopEnd-6]
	_ = x[RunningState_RunCallBegin-7]
	_ = x[RunningState_RunCallEnd-8]
	_ = x[RunningState_RunGCBegin-9]
	_ = x[RunningState_RunGCEnd-10]
	_ = x[RunningState_Terminating-11]
	_ = x[RunningState_Terminated-12]
}

const _RunningState_name = "RunningState_BirthRunningState_StartingRunningState_StartedRunningState_FrameLoopBeginRunningState_FrameUpdateBeginRunningState_FrameUpdateEndRunningState_FrameLoopEndRunningState_RunCallBeginRunningState_RunCallEndRunningState_RunGCBeginRunningState_RunGCEndRunningState_TerminatingRunningState_Terminated"

var _RunningState_index = [...]uint16{0, 18, 39, 59, 86, 115, 142, 167, 192, 215, 238, 259, 283, 306}

func (i RunningState) String() string {
	if i < 0 || i >= RunningState(len(_RunningState_index)-1) {
		return "RunningState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunningState_name[_RunningState_index[i]:_RunningState_index[i+1]]
}
