// Code generated by "stringer -type RunningStatus"; DO NOT EDIT.

package runtime

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RunningStatus_Birth-0]
	_ = x[RunningStatus_Starting-1]
	_ = x[RunningStatus_Started-2]
	_ = x[RunningStatus_FrameLoopBegin-3]
	_ = x[RunningStatus_FrameUpdateBegin-4]
	_ = x[RunningStatus_FrameUpdateEnd-5]
	_ = x[RunningStatus_FrameLoopEnd-6]
	_ = x[RunningStatus_RunCallBegin-7]
	_ = x[RunningStatus_RunCallEnd-8]
	_ = x[RunningStatus_RunGCBegin-9]
	_ = x[RunningStatus_RunGCEnd-10]
	_ = x[RunningStatus_Terminating-11]
	_ = x[RunningStatus_Terminated-12]
	_ = x[RunningStatus_ActivatingAddIn-13]
	_ = x[RunningStatus_AddInActivated-14]
	_ = x[RunningStatus_DeactivatingAddIn-15]
	_ = x[RunningStatus_AddInDeactivated-16]
	_ = x[RunningStatus_ActivatingEntity-17]
	_ = x[RunningStatus_EntityActivated-18]
	_ = x[RunningStatus_DeactivatingEntity-19]
	_ = x[RunningStatus_EntityDeactivated-20]
	_ = x[RunningStatus_EntityInitComponents-21]
	_ = x[RunningStatus_EntityAddComponents-22]
}

const _RunningStatus_name = "RunningStatus_BirthRunningStatus_StartingRunningStatus_StartedRunningStatus_FrameLoopBeginRunningStatus_FrameUpdateBeginRunningStatus_FrameUpdateEndRunningStatus_FrameLoopEndRunningStatus_RunCallBeginRunningStatus_RunCallEndRunningStatus_RunGCBeginRunningStatus_RunGCEndRunningStatus_TerminatingRunningStatus_TerminatedRunningStatus_ActivatingAddInRunningStatus_AddInActivatedRunningStatus_DeactivatingAddInRunningStatus_AddInDeactivatedRunningStatus_ActivatingEntityRunningStatus_EntityActivatedRunningStatus_DeactivatingEntityRunningStatus_EntityDeactivatedRunningStatus_EntityInitComponentsRunningStatus_EntityAddComponents"

var _RunningStatus_index = [...]uint16{0, 19, 41, 62, 90, 120, 148, 174, 200, 224, 248, 270, 295, 319, 348, 376, 407, 437, 467, 496, 528, 559, 593, 626}

func (i RunningStatus) String() string {
	if i < 0 || i >= RunningStatus(len(_RunningStatus_index)-1) {
		return "RunningStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunningStatus_name[_RunningStatus_index[i]:_RunningStatus_index[i+1]]
}
