// Code generated by "stringer -type RunningEvent"; DO NOT EDIT.

package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RunningEvent_Birth-0]
	_ = x[RunningEvent_Starting-1]
	_ = x[RunningEvent_Started-2]
	_ = x[RunningEvent_Heartbeat-3]
	_ = x[RunningEvent_Terminating-4]
	_ = x[RunningEvent_Terminated-5]
	_ = x[RunningEvent_AddInActivating-6]
	_ = x[RunningEvent_AddInActivated-7]
	_ = x[RunningEvent_AddInDeactivating-8]
	_ = x[RunningEvent_AddInDeactivated-9]
	_ = x[RunningEvent_EntityPTDeclared-10]
	_ = x[RunningEvent_ComponentPTDeclared-11]
	_ = x[RunningEvent_EntityRegistered-12]
	_ = x[RunningEvent_EntityDeregistered-13]
}

const _RunningEvent_name = "RunningEvent_BirthRunningEvent_StartingRunningEvent_StartedRunningEvent_HeartbeatRunningEvent_TerminatingRunningEvent_TerminatedRunningEvent_AddInActivatingRunningEvent_AddInActivatedRunningEvent_AddInDeactivatingRunningEvent_AddInDeactivatedRunningEvent_EntityPTDeclaredRunningEvent_ComponentPTDeclaredRunningEvent_EntityRegisteredRunningEvent_EntityDeregistered"

var _RunningEvent_index = [...]uint16{0, 18, 39, 59, 81, 105, 128, 156, 183, 213, 242, 271, 303, 332, 363}

func (i RunningEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RunningEvent_index)-1 {
		return "RunningEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunningEvent_name[_RunningEvent_index[idx]:_RunningEvent_index[idx+1]]
}
