// Code generated by "stringer -type RunningState"; DO NOT EDIT.

/*
 * This file is part of Golaxy Distributed Service Development Framework.
 *
 * Golaxy Distributed Service Development Framework is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 2.1 of the License, or
 * (at your option) any later version.
 *
 * Golaxy Distributed Service Development Framework is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with Golaxy Distributed Service Development Framework. If not, see <http://www.gnu.org/licenses/>.
 *
 * Copyright (c) 2024 pangdogs.
 */
 
package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RunningState_Birth-0]
	_ = x[RunningState_Starting-1]
	_ = x[RunningState_Started-2]
	_ = x[RunningState_Terminating-3]
	_ = x[RunningState_Terminated-4]
}

const _RunningState_name = "RunningState_BirthRunningState_StartingRunningState_StartedRunningState_TerminatingRunningState_Terminated"

var _RunningState_index = [...]uint8{0, 18, 39, 59, 83, 106}

func (i RunningState) String() string {
	if i < 0 || i >= RunningState(len(_RunningState_index)-1) {
		return "RunningState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunningState_name[_RunningState_index[i]:_RunningState_index[i+1]]
}
