// Code generated by "stringer -type RunningEvent"; DO NOT EDIT.

package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RunningEvent_Birth-0]
	_ = x[RunningEvent_Starting-1]
	_ = x[RunningEvent_Started-2]
	_ = x[RunningEvent_Terminating-3]
	_ = x[RunningEvent_Terminated-4]
	_ = x[RunningEvent_AddInActivating-5]
	_ = x[RunningEvent_AddInActivated-6]
	_ = x[RunningEvent_AddInDeactivating-7]
	_ = x[RunningEvent_AddInDeactivated-8]
	_ = x[RunningEvent_EntityPTDeclared-9]
	_ = x[RunningEvent_ComponentPTDeclared-10]
	_ = x[RunningEvent_EntityRegistered-11]
	_ = x[RunningEvent_EntityUnregistered-12]
}

const _RunningEvent_name = "RunningEvent_BirthRunningEvent_StartingRunningEvent_StartedRunningEvent_TerminatingRunningEvent_TerminatedRunningEvent_AddInActivatingRunningEvent_AddInActivatedRunningEvent_AddInDeactivatingRunningEvent_AddInDeactivatedRunningEvent_EntityPTDeclaredRunningEvent_ComponentPTDeclaredRunningEvent_EntityRegisteredRunningEvent_EntityUnregistered"

var _RunningEvent_index = [...]uint16{0, 18, 39, 59, 83, 106, 134, 161, 191, 220, 249, 281, 310, 341}

func (i RunningEvent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_RunningEvent_index)-1 {
		return "RunningEvent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunningEvent_name[_RunningEvent_index[idx]:_RunningEvent_index[idx+1]]
}
