// Code generated by "stringer -type RunningState"; DO NOT EDIT.

package service

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RunningState_Birth-0]
	_ = x[RunningState_Starting-1]
	_ = x[RunningState_Started-2]
	_ = x[RunningState_Terminating-3]
	_ = x[RunningState_Terminated-4]
	_ = x[RunningState_AddInActivating-5]
	_ = x[RunningState_AddInActivated-6]
	_ = x[RunningState_AddInDeactivating-7]
	_ = x[RunningState_AddInDeactivated-8]
}

const _RunningState_name = "RunningState_BirthRunningState_StartingRunningState_StartedRunningState_TerminatingRunningState_TerminatedRunningState_AddInActivatingRunningState_AddInActivatedRunningState_AddInDeactivatingRunningState_AddInDeactivated"

var _RunningState_index = [...]uint8{0, 18, 39, 59, 83, 106, 135, 163, 194, 224}

func (i RunningState) String() string {
	if i < 0 || i >= RunningState(len(_RunningState_index)-1) {
		return "RunningState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RunningState_name[_RunningState_index[i]:_RunningState_index[i+1]]
}
