// Code generated by eventcode --decl_file=component_event.go --not_import_core gen_emit --package=core; DO NOT EDIT.

package core

func emitEventComponentDestroySelf(event IEvent, comp Component) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IfaceCache) bool {
		Cache2Iface[eventComponentDestroySelf](delegate).onComponentDestroySelf(comp)
		return true
	})
}
