// Code generated by eventcode --decl_file=entity_event.go --not_import_core gen_emit --package=core; DO NOT EDIT.

package core

func EmitEventEntityDestroySelf(event IEvent, entity Entity) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IFaceCache) bool {
		Cache2IFace[eventEntityDestroySelf](delegate).onEntityDestroySelf(entity)
		return true
	})
}
