// Code generated by eventcode -decl entity_componentmgr_event.go -core  -emit_package core -export_emit=false; DO NOT EDIT.

package core

func emitEventCompMgrAddComponents(event IEvent, entity Entity, components []Component) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IFaceCache) bool {
		Cache2IFace[EventCompMgrAddComponents](delegate).OnCompMgrAddComponents(entity, components)
		return true
	})
}

func emitEventCompMgrRemoveComponent(event IEvent, entity Entity, component Component) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IFaceCache) bool {
		Cache2IFace[EventCompMgrRemoveComponent](delegate).OnCompMgrRemoveComponent(entity, component)
		return true
	})
}
