// Code generated by eventcode --decl_file=entity_event.go --not_import_core gen_emit --package=core; DO NOT EDIT.

package core

func emitEventEntityDestroySelf(event IEvent, entity Entity) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IfaceCache) bool {
		Cache2Iface[eventEntityDestroySelf](delegate).onEntityDestroySelf(entity)
		return true
	})
}
