// Code generated by eventcode -decl entity_event.go -core  -emit_package core -export_emit=false; DO NOT EDIT.
package core

func emitEventEntityDestroySelf(event IEvent, entity Entity) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IFaceCache) bool {
		Cache2IFace[eventEntityDestroySelf](delegate).onEntityDestroySelf(entity)
		return true
	})
}
