// Code generated by eventcode --decl_file=entity_componentmgr_event.go --not_import_core gen_emit --package=core; DO NOT EDIT.

package core

func emitEventCompMgrAddComponents(event IEvent, entity Entity, components []Component) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IfaceCache) bool {
		Cache2Iface[EventCompMgrAddComponents](delegate).OnCompMgrAddComponents(entity, components)
		return true
	})
}

func emitEventCompMgrRemoveComponent(event IEvent, entity Entity, component Component) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IfaceCache) bool {
		Cache2Iface[EventCompMgrRemoveComponent](delegate).OnCompMgrRemoveComponent(entity, component)
		return true
	})
}
