// Code generated by eventcode --decl_file=runtime_event.go --not_import_core gen_emit --package=core --default_export=0; DO NOT EDIT.

package core

func emitEventUpdate(event IEvent) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IfaceCache) bool {
		Cache2Iface[eventUpdate](delegate).Update()
		return true
	})
}

func emitEventLateUpdate(event IEvent) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IfaceCache) bool {
		Cache2Iface[eventLateUpdate](delegate).LateUpdate()
		return true
	})
}
