// Code generated by eventcode -decl runtime_event.go -core  -emit_package core -export_emit=false; DO NOT EDIT.

package core

func emitEventUpdate(event IEvent) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IFaceCache) bool {
		Cache2IFace[eventUpdate](delegate).Update()
		return true
	})
}

func emitEventLateUpdate(event IEvent) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate IFaceCache) bool {
		Cache2IFace[eventLateUpdate](delegate).LateUpdate()
		return true
	})
}
