// Code generated by "stringer -type PluginState"; DO NOT EDIT.

package plugin

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PluginState_Loaded-0]
	_ = x[PluginState_Active-1]
	_ = x[PluginState_Inactive-2]
}

const _PluginState_name = "PluginState_BirthPluginState_AlivePluginState_Death"

var _PluginState_index = [...]uint8{0, 17, 34, 51}

func (i PluginState) String() string {
	if i < 0 || i >= PluginState(len(_PluginState_index)-1) {
		return "PluginState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PluginState_name[_PluginState_index[i]:_PluginState_index[i+1]]
}
