package main

import (
	"bytes"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
	"strings"
)

func genEmit(ctx *_CommandContext) {
	emitFile := ctx.EmitDir

	if emitFile == "" {
		emitFile = strings.TrimSuffix(ctx.DeclFile, ".go") + "_emit_code.go"
	} else {
		emitFile = filepath.Dir(ctx.DeclFile) + string(filepath.Separator) + ctx.EmitDir + string(filepath.Separator) + filepath.Base(strings.TrimSuffix(ctx.DeclFile, ".go")) + "_emit_code.go"
	}

	emitCode := &bytes.Buffer{}

	// 生成注释
	{
		fmt.Fprintf(emitCode, `// Code generated by %s%s; DO NOT EDIT.

package %s
`, strings.TrimSuffix(filepath.Base(os.Args[0]), filepath.Ext(os.Args[0])),
			func() (args string) {
				for _, arg := range os.Args[1:] {
					if arg == "" {
						arg = `""`
					}
					args += " " + arg
				}
				return
			}(),
			ctx.EmitPackage)
	}

	// 生成import
	{
		importCode := &bytes.Buffer{}
		hasImport := false

		fmt.Fprintf(importCode, "\nimport (")

		if !ctx.NotImportCore {
			hasImport = true
			fmt.Fprintf(importCode, `
	%s "github.com/pangdogs/galaxy/core"`, ctx.CoreAlias)
		}

		for _, imp := range ctx.FileAst.Imports {
			begin := ctx.FileSet.Position(imp.Pos())
			end := ctx.FileSet.Position(imp.End())

			impStr := string(ctx.FileData[begin.Offset:end.Offset])

			if !ctx.NotImportCore && strings.Contains(impStr, "github.com/pangdogs/galaxy/core") {
				continue
			}

			hasImport = true
			fmt.Fprintf(importCode, "\n\t%s", impStr)
		}

		fmt.Fprintf(importCode, "\n)\n")

		if hasImport {
			fmt.Fprintf(emitCode, importCode.String())
		}
	}

	// 解析事件定义
	eventDeclTab := _EventDeclTab{}
	eventDeclTab.Parse(ctx)

	// core包前缀
	corePrefix := ""
	if !ctx.NotImportCore && ctx.CoreAlias != "." {
		corePrefix = ctx.CoreAlias + "."
	}

	// 生成事件发送代码
	for _, eventDecl := range eventDeclTab {
		// 是否导出事件发送代码
		exportEmitStr := "emit"
		if ctx.EmitDefExport {
			exportEmitStr = "Emit"
		}

		if strings.Contains(eventDecl.Comment, "[EmitExport]") {
			exportEmitStr = "Emit"
		} else if strings.Contains(eventDecl.Comment, "[EmitUnExport]") {
			exportEmitStr = "emit"
		}

		// 生成代码
		if eventDecl.FuncHasRet {
			fmt.Fprintf(emitCode, `
func %[9]s%[1]s%[7]s(event %[6]sIEvent%[4]s) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate %[6]sIfaceCache) bool {
		return %[6]sCache2Iface[%[2]s%[8]s](delegate).%[3]s(%[5]s)
	})
}
`, strings.Title(eventDecl.Name), eventDecl.Name, eventDecl.FuncName, eventDecl.FuncParamsDecl, eventDecl.FuncParams, corePrefix, eventDecl.FuncTypeParamsDecl, eventDecl.FuncTypeParams, exportEmitStr)

		} else {
			fmt.Fprintf(emitCode, `
func %[9]s%[1]s%[7]s(event %[6]sIEvent%[4]s) {
	if event == nil {
		panic("nil event")
	}
	event.Emit(func(delegate %[6]sIfaceCache) bool {
		%[6]sCache2Iface[%[2]s%[8]s](delegate).%[3]s(%[5]s)
		return true
	})
}
`, strings.Title(eventDecl.Name), eventDecl.Name, eventDecl.FuncName, eventDecl.FuncParamsDecl, eventDecl.FuncParams, corePrefix, eventDecl.FuncTypeParamsDecl, eventDecl.FuncTypeParams, exportEmitStr)
		}

		fmt.Printf("Emit: %s\n", eventDecl.Name)
	}

	os.MkdirAll(filepath.Dir(emitFile), os.ModePerm)

	if err := ioutil.WriteFile(emitFile, emitCode.Bytes(), os.ModePerm); err != nil {
		panic(err)
	}
}
